Test failed on a recent PR that touched unrelated code:
https://github.com/quantumlib/Cirq/actions/runs/6592721242/job/17913909526?pr=6322#step:6:330
If it's one isolated case, it's possibly due to the timeout being too short (5s). If this happens more often, we could consider increasing the timeout to see if it helps.
5 seconds seems like a very generous timeout for a basic unit test. Do you think there's something happening in this test that could really take that long?
That's true. I also wonder if something else on the Windows machine could have kept compute resources away from the test to have caused the delay.
I couldn't reproduce the failure after repeating the test 1000 times on my Linux machine using pytest --count 1000 -x cirq-google/cirq_google/engine/stream_manager_test.py -k test_submit_with_non_retryable_stream_breakage_raises_error. Perhaps something unique to the Windows environment is triggering the test failure. I'd like to wait until the flake rate is higher, though, to investigate further, especially given it's hard to reproduce locally.
I couldn't reproduce the failure after repeating the test 1000 times on my Linux machine using pytest --count 1000 ...
The --count option seems to rerun the test with the same random seed (from pytest-randomly).
It may be worthwhile to rerun the pytest process rather then use its --count option.
This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 30 days
Issue closed due to inactivity.
