This occurs for a variety of (random) circuits and backends, but is not consistent for different random seeds.
qiskit.transpiler.exceptions.TranspilerError: 'Maximum iteration reached. max_iteration=1000'
Seems to be similar to #5753, #5832, #5627 and maybe #5644.
Attached is a log file of one of the runs that resulted in the error for ibmq_bogota connectivity.
maximum_iters_transpiler_error.log
This is the full transpiler method call I used: compiled_circuit = transpile(circuit, coupling_map=CouplingMap(hardware_connectivity), optimization_level=3, basis_gates=["x", "sx", "cx", "rz"], initial_layout=[0, 1, 2, 3, 4]
Do you have an example of a circuit which failed? I tried but wasn't able to replicate this with the following code:
I do not know what the cause of this is, but I can not consistently replicate the error with fixed seed_transpiler values. Maybe there is a component which is not seeded by the seed_transpiler ?
Here is a qasm file (I could not upload with the .qasm extension) of a circuit which sometimes produces this error.
example.txt
I have been able to reproduce the error using this code (typically occurs after about 5 seed values):
Thanks for the additional info. I still wasn't able to replicate (I ran to both seed=100 on python 3.6 and 3.7) though I'm on MacOS 10.15, so it's possible its is a dependency problem. Can you post your np.__version__, np.show_config() and a transpile log including the callback from #5627 (comment) ?
Can you try with several different random seeds (as in the code I posted above)? I am observing stochastic results, even with the fixed random seed. For that reason, I can not consistently replicate the error (and therefore I can not post a consistent transpile log). np.__version__ is 1.21.1 and np.show_config() is
My numpy version and config are similar to yours, and I tried on python 3.6 and 3.7 for every seed_transpiler in range(100) but still wasn't able to replicate. If you can run with the callback and try to capture one successful log, and one failing log, that would give us a place to start looking. Otherwise, we might need to find someone else who can replicate (maybe with the same hardware or MacOS version) to be able to debug further.
I have not been able to reproduce as well.
Attached is the output from running this code:
The program threw the maximum iteration qiskit.transpiler.exceptions.TranspilerError at seed 3. If you look at callback.txt, you can see where the different seed values are being printed out near the top of the file. Seed values 0, 1, and 2 worked without any error (seeds 1 and 2 completed in a small number of steps), and then seed 3 gets stuck for 1,000 iterations.
Do you have an example of a circuit which failed? I tried but wasn't able to replicate this with the following code:
I get the following output in this case:
@epelofske-LANL Try this callback to save the problematic circuit:
One example of a circuit that failed is attached in the above posts as example.txt (it is a qasm file).
we were not able to reproduce this issue and the information. Please, check again with Qiskit main. If the problem persists, reopen this issue. From callback.txt it seems like UnitarySynthesis is not being deterministic. But it is very hard to know.
@1ucian0 I am still encountering the error - but it seems to platform dependent. Linux installations are not finding this error, but my macOS installation is still encountering the error.
This error seems to not occur (or at least occurs less) when the transpiler option optimization_level is set to 2, instead of 3.
This appears to be a problem with the order of the specified initial layout. My fix for this is to randomly shuffle the initial layout:
Eventually this method works after a few tries.
