I open the dashboard as the documentation  says, and successfully makes it print ''hello world''

however, when I create a file which hope the ttl windows on dashboard will react,(the file is in ~/artiq-master/repository )

open the dashboard, there is a error

and the dashboard

click submit, then

and the ttl windows on dashboard has no response.
and, on a VMware run linux Ubuntu，the dashboard can not be open

open the dashboard, there is a error
What error? The experiment rename? The message describes what the problem is: you have created two experiments that have the same name. You should change the name of one of them in your code, or delete one of them.
and the ttl windows on dashboard has no response.
The TTL window has a slow refresh rate. Try delays of ~seconds instead of 2µs.
and, on a VMware run linux Ubuntu，the dashboard can not be open
Unfortunately we cannot provide free support for this last problem. If you want this fixed, consider funding #652.
ok. I will have a try. thanks
no, now there is error

theMgmtTutorial1 is the name it changed  fromrtio.py, and Mgmt_Tutorial.py  is the name of the file I use to test the dashboard(print hello world)
and, can the dashboard function without the kc705 been connected through internet?
heMgmtTutorial1 is the name it changed fromrtio.py, and Mgmt_Tutorial.py is the name of the file I use to test the dashboard(print hello world)
Right-click on the experiment list in the explorer and trigger a rescan.
and, can the dashboard function without the kc705 been connected through internet?
Yes.
it still raise the same error
Please post detailed steps explaining how I can reproduce the problem.
after open the dashboard, and the cmd windows is same as upon pictures shows,

Right-click on the experiment list in the explorer and trigger a rescan
I click scan repository HEAD
because it says Renaming class 'MgmtTutorial' in 'rtio.py' to 'Management tutorial1', then I chose the
Management tutorial1 and click submit, and then the cmd of artiq_master shows ERROR:master:artiq.master.scheduler:got worker exception in prepare stage, deleting RID 49
That's not enough for me to reproduce it, e.g. I don't have your experiments. I need detailed instructions that start from a blank ARTIQ installation.
And I need information about what that worker exception was. It should be in the log.


I see three experiments in your screenshot. Are they all needed to reproduce the problem? if yes then I need all three. If no then please delete the other ones and give me minimal instructions.
And please post the text of experiments, not a screenshot, so I can copy-paste it.
the rtio.py:
from artiq.experiment import *
class Tutorial(EnvExperiment):
def build(self):
self.setattr_device("core")
self.setattr_device("ttl0")
the mgmt_tutorial.py
from artiq.experiment import *
class MgmtTutorial(EnvExperiment):
"""Management tutorial"""
def build(self):
pass  # no devices used
and it is strange that I only put these two experiments in repository but the explorer shows three
the mgmt_tutorial is to print hello world, the  mgmt_tutorial1 is to test the ttl(change name from rtio.py)when I submit the Tutorial, it says can not find the cygwin1.dll
that is what are in the repository

and, about the problem on ubuntu, I do as the guide says 'making a py35 environment' the same as I do on windows.

and we have pay the fee for Technical consultation when we buy the sinara
What is your email address?
it says can not find the cygwin1.dll
Did you update to 3.6?
no. actually I make a python3.5 environment as the documentation says. should I create a python 3.6 environment use conda create -n py36 python=3.6 anaconda?
I meant ARTIQ 3.6, not Python 3.6.
no, I use artiq3.4. how to update?

the order can not be used for a long time, says files can not be found.
or I can download a new 3.6 use conda create -n artiq-main artiq-kc705-nist_clock , derectly making a new environment.
conda create -n artiq-new artiq=3.6 artiq-kc705-nist_clock=3.6
I cannot reproduce your naming problem. I have only two experiments as expected, and they both run correctly. Please give me instructions starting from a blank ARTIQ installation with a master that has just been run.

ok. after installing 3.6 as the order you give,  I will try it on a new version, hoping the new version will solve the problem. the installing will take a long time, I will let you know once I reproduce the step above.
thanks a lot.
The software also behaves correctly when I make a copy of the experiment Management tutorial (renames one of them, they both can still run, and there is no bug when rescanning the repository).
Also reflash the board after upgrading.
ok. hope the upgrading will solve the problem.
thanks.
It should fix the cygwin one, but nothing has changed regarding repository management, so I think the experiment name issue will persist.
here is every move:
activate artiq-new;   cd C:\Users\18926\AppData\Local\conda\conda\envs\artiq-new\artiq-master
artiq_master;  and open a new cmd, activate the artiq-new,  cd C:\Users\18926\AppData\Local\conda\conda\envs\artiq-new\artiq-master ; artiq_dashboard

and then I click submit, the experiment is same as rtio.py above,
all of the log since the dashboard been opened:(the chinese means ''error sem timeout''


So, it seems that the first problem you were reporting is resolved: There are no more incorrect names in the explorer, and the experiment starts when you submit it.
The two errors you now have are:
Is the core device (the KC705 board) properly set up and connected to the network? Can you ping it? Did you set its IP address in device_db.py?
well, we didn't connect to the kc705(as you said it do not have to)
and the problem is ''get worker exception'', and, the ttl window has no respons
What I meant is, if your experiment does not need a core device, then you do not need a core device for the dashboard either. The experiment you are currently running needs a core device.
so the dashboard can not simulate the board?
There is limited simulation support (see artiq/examples/no_hardware/repository/simple_simulation.py), but no one finds it very useful, so it is not very developed and in particular not integrated with the dashboard.
Arguably, blinking the TTL panel when no device is connected and an experiment with the core device is run is not a useful feature.
all right, I will get a kc705 and test it.(unluckily I have to wait for few days and that is why I hope the dashboard can simulate the board).
thanks
Try experiments that do not need the core device and play with the datasets and applets, see e.g. artiq/examples/no_hardware/repository/flopping_f_simulation.py.
that seems work well.
by the way, where can I find the pin setting in the documentation so that I can know where to use a Oscilloscope to detect the ttl out?  is it in 'core language reference'?
https://github.com/m-labs/artiq/blob/master/artiq/gateware/nist_clock.py
https://github.com/m-labs/artiq/blob/master/artiq/gateware/nist_qc2.py
and the manual.
Note that ttl, 0 in nist_clock is not necessarily ttl0 in the device database (check the manual).
I find that 'binaries' is in the wrong dictionary in artiq-new
it suppose to be C:\Users\18926\AppData\Local\conda\conda\envs\artiq-new\lib\site-packages\artiq\binaries,
but now in C:\Users\18926\AppData\Local\conda\conda\envs\artiq-new\lib\python3.5\site-packages\artiq
Can you give more details? What exactly did you do?
well， I 'm not sure what happened, maybe there are too many version artiq on my computer so the artiq-new raise some error. However, now I remove all the old artiq and install the 3.6 and all the problem solved.
Good. Are you in the new ARTIQ Wechat group? There are other Chinese-speaking users there who might help you, especially WIPM who have a rather developed ARTIQ installation. If not give me your ID and I will add you.
Yes I am in it. thanks a lot.
