Also affects QubitOrder.as_qubit_order().  I believe the issue is on line 77 of cirq/ops/qubit_order.py.
Example:
The example raises ValueError: Unexpected extra qubits: {cirq.LineQubit(3)}. because reversed() is an iterator and QubitOrder tried to iterate it twice.
