Program:
import numpy as np
from qiskit import *
from qiskit import IBMQ
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import BasicAer, execute
from qiskit.quantum_info import Pauli, state_fidelity, basis_state, process_fidelity
from qiskit import compile
from qiskit.providers.ibmq import least_busy
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
import codecs
from qiskit.tools.visualization import circuit_drawer
import sys
print('                         Dictionary for Qiskit vvv')
print('                         https://qiskit.org/documentation/terra/quantum_circuits.html')
qr = QuantumRegister(3)
cr = ClassicalRegister(3)
circuit = QuantumCircuit(qr, cr)
circuit.x(qr[0])
circuit.x(qr[1])
circuit.ccx(qr[0], qr[1], qr[2])
circuit.cx(qr[0], qr[1])
circuit.measure(qr, cr)
print(circuit)
print(qr.size)
print(cr.size)
RESULT:
Dictionary for Qiskit vvv
https://qiskit.org/documentation/terra/quantum_circuits.html
Traceback (most recent call last):
File "draw.py", line 27, in 
print(circuit)
File "C:\Users\micro\Anaconda3\envs\Quantum\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 14-18: character maps to 
Supposed to output circuit in ASCII format.
I will have access to a Windows machine tomorrow, so I can have a look to this issue.
I could not reproduce the issue. Could it be the coding of your console? Maybe we should move to utf-8 output anyway.

@1ucian0 Thank You for writing back. If it is the coding of the console causing the error, is there a link where I can install older versions of the Anaconda terminal?
I'm tested with the last version of Anaconda. Not a Windows expert here, but probably you can change the enconding of the console in the console property menu.
Resolved! Created a new environment with Python 3.6 instead of Python 3.5. conda create --name work python=3.6 and reinstalled Qiskit. works like a charm now.
So the problem is with Python 3.5? I will check it!
still cannot reproduce it. Feel free to reopen this if necessary. Thanks!
