Lately I've been getting a flake on cirq-google/cirq_google/engine/engine_client_test.py
It has the strange behavior that a different number of the tests in this file fail.
Here is a typical failure
@maffoo @dstrain115 any idea what might be causing this, it looks to be coming from AsyncMock.
I have not been able to reproduce the flakiness on either python 3.8.8 or python 3.9.13. How are you invoking pytest? I tried just running the cirq_google/engine/engine_client_test.py tests and also all tests in cirq_google/engine.
This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 30 days
Issue closed due to inactivity.
