Errors in test/verification/test_entanglemet.py:
https://github.com/Qiskit/qiskit-ignis/blob/1c6f4c1eb2648341637e1ba6e390258bb3c3478c/test/verification/test_entanglemet.py#L45
https://github.com/Qiskit/qiskit-ignis/blob/1c6f4c1eb2648341637e1ba6e390258bb3c3478c/test/verification/test_entanglemet.py#L55
https://github.com/Qiskit/qiskit-ignis/blob/1c6f4c1eb2648341637e1ba6e390258bb3c3478c/qiskit/ignis/verification/entanglement/linear.py#L80
https://github.com/Qiskit/qiskit-ignis/blob/1c6f4c1eb2648341637e1ba6e390258bb3c3478c/qiskit/ignis/verification/entanglement/linear.py#L122
Test test/verification/test_entanglement.py. I ran with pytest, but the errors should be universal.
Test should pass
Looks like errors stem from #328
Thanks @drewrisinger , I'll look into it. It passed on my end multiple times, I'll check what went wrong
I'm curious why this wasn't caught by Travis/Azure CI tests?
@chriseclectic I just took a quick look, the reason is that the test/verification directory doesn't have an __init__.py file, so it's not importable via python and unittest discovery didn't see the test module and didn't try to run it. Pytest doesn't use python's stdlib unittest discovery and instead implements it's own test discovery which scans the directory tree which is why the reproduce steps found this but CI didn't
@chriseclectic it looks like this is the same reason why #385 wasn't caught in CI (missing __init__.py in test/logging directory). After a quick look through source on master, looks like test/{logging, verification} are the only ones missing __init__.py.
@mtreinish @drewrisinger thanks for spotting that! I guess we need to add some extra init files then.
