Some unittests fail sometimes, but succeed on re-run. Maybe we have a thread-sync bug?
This could have been caused by a bug fixed in #34 -- not joining the daemon threads on exit. For now, I'm marking this as closed.
